$ANSIBLE_VAULT;1.1;AES256
37356232316233376662663237636362633764346165626135653534323930373634623331316266
3764343938653838653462356261386664343432373666390a343536333465663333323430376531
38383239613163383163623964613138323138343638393836383166653864316135653632363337
3231656262366436640a356635336664333466336161326163626338393130613734323562643434
37323462343465363436373138653336323732353634623363373132373561356639373032333662
37303835353561313062613238353036313865633465393863333330366266643634393765383538
37343735633463366133313933396661393439363233366563366237323863323031663137663164
65366162393366353863336235623431616535653638396466303635313339356330373438313235
35336634393565363430633863336636363137333663373438616566643339663030363137363164
3163326161313130386266383739653962373634366437383561
